
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucmvhjawucyznchetekh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjbXZoamF3dWN5em5jaGV0ZWtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMzkxNjAsImV4cCI6MjA1NzcxNTE2MH0.X5MgR734lS9Luu8fNMHvNfjYNqU9KBTDtta7QlW4cYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  },
  global: {
    headers: {
      'x-application-name': 'BladiTV',
      'x-application-version': '1.0.0'
    }
  }
});
